apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kupdater-leader-election-rolebinding
  namespace: kupdater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kupdater-leader-election-role
subjects:
- kind: ServiceAccount
  name: kupdater-operator
  namespace: kupdater
