apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: operator
  name: kupdater-operator-metrics-service
  namespace: kupdater
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: operator
